--------------------------------------------------------
-- Archivo creado  - sábado-abril-01-2017   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table CAJERO
--------------------------------------------------------

  CREATE TABLE "RESTAURANTE"."CAJERO" 
   (	"ID" NUMBER(*,0), 
	"USUARIO" VARCHAR2(20 BYTE), 
	"CONTRASEÑA" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"GENERO" VARCHAR2(10 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"CODIGO_POSTAL" NUMBER(*,0), 
	"NUMERO_TELEFONICO" NUMBER(*,0), 
	"ASISTENCIA" VARCHAR2(10 BYTE), 
	"IDGERENTE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CHEF
--------------------------------------------------------

  CREATE TABLE "RESTAURANTE"."CHEF" 
   (	"ID" NUMBER(*,0), 
	"USUARIO" VARCHAR2(20 BYTE), 
	"CONTRASEÑA" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"GENERO" VARCHAR2(10 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"CODIGO_POSTAL" NUMBER(*,0), 
	"NUMERO_TELEFONICO" NUMBER(*,0), 
	"ASISTENCIA" VARCHAR2(10 BYTE), 
	"IDGERENTE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "RESTAURANTE"."CLIENTE" 
   (	"ID" NUMBER(*,0), 
	"USUARIO" VARCHAR2(20 BYTE), 
	"CONTRASEÑA" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"NUMERO_TELEFONICO" NUMBER(*,0), 
	"CORREO_ELECTRONICO" VARCHAR2(20 BYTE), 
	"NUMERO_ORDEN" NUMBER(*,0), 
	"FOLIO_TICKET" NUMBER(*,0), 
	"ID_RESERVACION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RESTAURANTE"."CLIENTE"."ID" IS 'PK';
   COMMENT ON COLUMN "RESTAURANTE"."CLIENTE"."NUMERO_ORDEN" IS 'FK1';
   COMMENT ON COLUMN "RESTAURANTE"."CLIENTE"."FOLIO_TICKET" IS 'FK2';
   COMMENT ON COLUMN "RESTAURANTE"."CLIENTE"."ID_RESERVACION" IS 'FK3';
--------------------------------------------------------
--  DDL for Table GERENTE
--------------------------------------------------------

  CREATE TABLE "RESTAURANTE"."GERENTE" 
   (	"IDGERENTE" NUMBER(*,0), 
	"USUARIO" VARCHAR2(20 BYTE), 
	"CONTRASEÑA" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"GENERO" VARCHAR2(10 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"CODIGO_POSTAL" NUMBER(*,0), 
	"NUMERO_TELEFONICO" NUMBER(*,0), 
	"ASISTENCIA" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MESERO
--------------------------------------------------------

  CREATE TABLE "RESTAURANTE"."MESERO" 
   (	"ID" NUMBER(*,0), 
	"USUARIO" VARCHAR2(20 BYTE), 
	"CONTRASEÑA" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"GENERO" VARCHAR2(10 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"CODIGO_POSTAL" NUMBER(*,0), 
	"NUMERO_TELEFONICO" NUMBER(*,0), 
	"ASISTENCIA" VARCHAR2(10 BYTE), 
	"IDGERENTE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ORDEN
--------------------------------------------------------

  CREATE TABLE "RESTAURANTE"."ORDEN" 
   (	"NUMERO_ORDEN" NUMBER(*,0), 
	"NUMERO_PLATILLO" NUMBER(*,0), 
	"TIPO_PLATILLO" VARCHAR2(30 BYTE), 
	"IDMESERO" NUMBER(*,0), 
	"FOLIO_TICKET" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PLATILLO
--------------------------------------------------------

  CREATE TABLE "RESTAURANTE"."PLATILLO" 
   (	"TIPO" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"INGREDIENTES" VARCHAR2(100 BYTE), 
	"TIEMPO_PREPARACION" VARCHAR2(25 BYTE), 
	"IDGERENTE" NUMBER(*,0), 
	"NUMERO_ORDEN" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "RESTAURANTE"."PRODUCTO" 
   (	"TIPO" VARCHAR2(30 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"NUMERO_PIEZA" NUMBER(*,0), 
	"FECHA_INGRESO" DATE, 
	"IDGERENTE" NUMBER(*,0), 
	"IDPROVEEDOR" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RESTAURANTE"."PRODUCTO"."TIPO" IS 'PK';
   COMMENT ON COLUMN "RESTAURANTE"."PRODUCTO"."IDGERENTE" IS 'FK';
   COMMENT ON COLUMN "RESTAURANTE"."PRODUCTO"."IDPROVEEDOR" IS 'FK2';
--------------------------------------------------------
--  DDL for Table PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "RESTAURANTE"."PROVEEDOR" 
   (	"NOMBRE" VARCHAR2(30 BYTE), 
	"CORREO_ELECTRONICO" VARCHAR2(40 BYTE), 
	"DIRECCION" VARCHAR2(40 BYTE), 
	"NUMERO_TELEFONICO" NUMBER(*,0), 
	"IDPRODUCTO" NUMBER(*,0), 
	"ID" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RECEPCIONISTA
--------------------------------------------------------

  CREATE TABLE "RESTAURANTE"."RECEPCIONISTA" 
   (	"ID" NUMBER(*,0), 
	"USUARIO" VARCHAR2(20 BYTE), 
	"CONTRASEÑA" VARCHAR2(20 BYTE), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"GENERO" VARCHAR2(10 BYTE), 
	"DIRECCION" VARCHAR2(50 BYTE), 
	"CODIGO_POSTAL" NUMBER(*,0), 
	"NUMERO_TELEFONICO" NUMBER(*,0), 
	"ASISTENCIA" VARCHAR2(10 BYTE), 
	"IDGERENTE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RESTAURANTE"."RECEPCIONISTA"."ID" IS 'PK';
   COMMENT ON COLUMN "RESTAURANTE"."RECEPCIONISTA"."IDGERENTE" IS 'FK';
--------------------------------------------------------
--  DDL for Table RESERVACION
--------------------------------------------------------

  CREATE TABLE "RESTAURANTE"."RESERVACION" 
   (	"ID" NUMBER, 
	"FECHA" DATE, 
	"HORA" VARCHAR2(20 BYTE), 
	"NUMERO_PERSONA" NUMBER, 
	"ID_CLIENTE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RESTAURANTE"."RESERVACION"."ID" IS 'PK';
   COMMENT ON COLUMN "RESTAURANTE"."RESERVACION"."ID_CLIENTE" IS 'FK';
--------------------------------------------------------
--  DDL for Table TICKET
--------------------------------------------------------

  CREATE TABLE "RESTAURANTE"."TICKET" 
   (	"FOLIO" NUMBER(*,0), 
	"FECHA" DATE, 
	"FORMA_PAGO" VARCHAR2(20 BYTE), 
	"TOTAL" FLOAT(126), 
	"ID_CLIENTE" NUMBER, 
	"NUMERO_ORDEN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON COLUMN "RESTAURANTE"."TICKET"."FOLIO" IS 'PK';
   COMMENT ON COLUMN "RESTAURANTE"."TICKET"."ID_CLIENTE" IS 'FK1';
   COMMENT ON COLUMN "RESTAURANTE"."TICKET"."NUMERO_ORDEN" IS 'FK2';
--------------------------------------------------------
--  DDL for Sequence DEMO_CUST_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RESTAURANTE"."DEMO_CUST_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORDER_ITEMS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RESTAURANTE"."DEMO_ORDER_ITEMS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_ORD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RESTAURANTE"."DEMO_ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 11 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_PROD_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RESTAURANTE"."DEMO_PROD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DEMO_USERS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "RESTAURANTE"."DEMO_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into RESTAURANTE.CAJERO
SET DEFINE OFF;
REM INSERTING into RESTAURANTE.CHEF
SET DEFINE OFF;
REM INSERTING into RESTAURANTE.CLIENTE
SET DEFINE OFF;
REM INSERTING into RESTAURANTE.GERENTE
SET DEFINE OFF;
REM INSERTING into RESTAURANTE.MESERO
SET DEFINE OFF;
REM INSERTING into RESTAURANTE.ORDEN
SET DEFINE OFF;
REM INSERTING into RESTAURANTE.PLATILLO
SET DEFINE OFF;
REM INSERTING into RESTAURANTE.PRODUCTO
SET DEFINE OFF;
REM INSERTING into RESTAURANTE.PROVEEDOR
SET DEFINE OFF;
REM INSERTING into RESTAURANTE.RECEPCIONISTA
SET DEFINE OFF;
REM INSERTING into RESTAURANTE.RESERVACION
SET DEFINE OFF;
REM INSERTING into RESTAURANTE.TICKET
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index CAJERO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESTAURANTE"."CAJERO_PK" ON "RESTAURANTE"."CAJERO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CHEF_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESTAURANTE"."CHEF_PK" ON "RESTAURANTE"."CHEF" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESTAURANTE"."CLIENTE_PK" ON "RESTAURANTE"."CLIENTE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index GERENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESTAURANTE"."GERENTE_PK" ON "RESTAURANTE"."GERENTE" ("IDGERENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index MESERO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESTAURANTE"."MESERO_PK" ON "RESTAURANTE"."MESERO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ORDEN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESTAURANTE"."ORDEN_PK" ON "RESTAURANTE"."ORDEN" ("NUMERO_ORDEN") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLATILLO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESTAURANTE"."PLATILLO_PK" ON "RESTAURANTE"."PLATILLO" ("TIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESTAURANTE"."PRODUCTO_PK" ON "RESTAURANTE"."PRODUCTO" ("TIPO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROVEEDOR_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESTAURANTE"."PROVEEDOR_PK1" ON "RESTAURANTE"."PROVEEDOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RECEPCIONISTA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESTAURANTE"."RECEPCIONISTA_PK" ON "RESTAURANTE"."RECEPCIONISTA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index RESERVACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESTAURANTE"."RESERVACION_PK" ON "RESTAURANTE"."RESERVACION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TICKET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "RESTAURANTE"."TICKET_PK" ON "RESTAURANTE"."TICKET" ("FOLIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Function CUSTOM_AUTH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "RESTAURANTE"."CUSTOM_AUTH" (p_username in VARCHAR2, p_password in VARCHAR2)
return BOOLEAN
is
  l_password varchar2(4000);
  l_stored_password varchar2(4000);
  l_expires_on date;
  l_count number;
begin
-- First, check to see if the user is in the user table
select count(*) into l_count from demo_users where user_name = p_username;
if l_count > 0 then
  -- First, we fetch the stored hashed password & expire date
  select password, expires_on into l_stored_password, l_expires_on
   from demo_users where user_name = p_username;

  -- Next, we check to see if the user's account is expired
  -- If it is, return FALSE
  if l_expires_on > sysdate or l_expires_on is null then

    -- If the account is not expired, we have to apply the custom hash
    -- function to the password
    l_password := custom_hash(p_username, p_password);

    -- Finally, we compare them to see if they are the same and return
    -- either TRUE or FALSE
    if l_password = l_stored_password then
      return true;
    else
      return false;
    end if;
  else
    return false;
  end if;
else
  -- The username provided is not in the DEMO_USERS table
  return false;
end if;
end;

/
--------------------------------------------------------
--  DDL for Function CUSTOM_HASH
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "RESTAURANTE"."CUSTOM_HASH" (p_username in varchar2, p_password in varchar2)
return varchar2
is
  l_password varchar2(4000);
  l_salt varchar2(4000) := 'MYG4OS03VZJHFWIKG7249SEEO92A1B';
begin

-- This function should be wrapped, as the hash algorhythm is exposed here.
-- You can change the value of l_salt or the method of which to call the
-- DBMS_OBFUSCATOIN toolkit, but you much reset all of your passwords
-- if you choose to do this.

l_password := utl_raw.cast_to_raw(dbms_obfuscation_toolkit.md5
  (input_string => p_password || substr(l_salt,10,13) || p_username ||
    substr(l_salt, 4,10)));
return l_password;
end;

/
--------------------------------------------------------
--  Constraints for Table CAJERO
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."CAJERO" ADD CONSTRAINT "CAJERO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RESTAURANTE"."CAJERO" MODIFY ("IDGERENTE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CAJERO" MODIFY ("ASISTENCIA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CAJERO" MODIFY ("NUMERO_TELEFONICO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CAJERO" MODIFY ("CODIGO_POSTAL" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CAJERO" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CAJERO" MODIFY ("GENERO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CAJERO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CAJERO" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CAJERO" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CAJERO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CHEF
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."CHEF" ADD CONSTRAINT "CHEF_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RESTAURANTE"."CHEF" MODIFY ("IDGERENTE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CHEF" MODIFY ("ASISTENCIA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CHEF" MODIFY ("NUMERO_TELEFONICO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CHEF" MODIFY ("CODIGO_POSTAL" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CHEF" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CHEF" MODIFY ("GENERO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CHEF" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CHEF" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CHEF" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CHEF" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."CLIENTE" MODIFY ("ID_RESERVACION" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RESTAURANTE"."CLIENTE" MODIFY ("FOLIO_TICKET" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CLIENTE" MODIFY ("NUMERO_TELEFONICO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CLIENTE" MODIFY ("NUMERO_ORDEN" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CLIENTE" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CLIENTE" MODIFY ("CORREO_ELECTRONICO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CLIENTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CLIENTE" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CLIENTE" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."CLIENTE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table GERENTE
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."GERENTE" ADD CONSTRAINT "GERENTE_PK" PRIMARY KEY ("IDGERENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RESTAURANTE"."GERENTE" MODIFY ("ASISTENCIA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."GERENTE" MODIFY ("NUMERO_TELEFONICO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."GERENTE" MODIFY ("CODIGO_POSTAL" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."GERENTE" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."GERENTE" MODIFY ("GENERO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."GERENTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."GERENTE" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."GERENTE" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."GERENTE" MODIFY ("IDGERENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MESERO
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."MESERO" ADD CONSTRAINT "MESERO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RESTAURANTE"."MESERO" MODIFY ("IDGERENTE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."MESERO" MODIFY ("ASISTENCIA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."MESERO" MODIFY ("NUMERO_TELEFONICO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."MESERO" MODIFY ("CODIGO_POSTAL" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."MESERO" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."MESERO" MODIFY ("GENERO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."MESERO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."MESERO" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."MESERO" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."MESERO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDEN
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."ORDEN" MODIFY ("FOLIO_TICKET" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."ORDEN" MODIFY ("IDMESERO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."ORDEN" ADD CONSTRAINT "ORDEN_PK" PRIMARY KEY ("NUMERO_ORDEN")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RESTAURANTE"."ORDEN" MODIFY ("TIPO_PLATILLO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."ORDEN" MODIFY ("NUMERO_PLATILLO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."ORDEN" MODIFY ("NUMERO_ORDEN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PLATILLO
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."PLATILLO" MODIFY ("NUMERO_ORDEN" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PLATILLO" ADD CONSTRAINT "PLATILLO_PK" PRIMARY KEY ("TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RESTAURANTE"."PLATILLO" MODIFY ("IDGERENTE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PLATILLO" MODIFY ("TIEMPO_PREPARACION" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PLATILLO" MODIFY ("INGREDIENTES" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PLATILLO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PLATILLO" MODIFY ("TIPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."PRODUCTO" MODIFY ("IDPROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RESTAURANTE"."PRODUCTO" MODIFY ("IDGERENTE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PRODUCTO" MODIFY ("FECHA_INGRESO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PRODUCTO" MODIFY ("NUMERO_PIEZA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PRODUCTO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PRODUCTO" MODIFY ("TIPO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."PROVEEDOR" ADD CONSTRAINT "PROVEEDOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RESTAURANTE"."PROVEEDOR" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PROVEEDOR" MODIFY ("IDPRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PROVEEDOR" MODIFY ("NUMERO_TELEFONICO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PROVEEDOR" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PROVEEDOR" MODIFY ("CORREO_ELECTRONICO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."PROVEEDOR" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECEPCIONISTA
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."RECEPCIONISTA" ADD CONSTRAINT "RECEPCIONISTA_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RESTAURANTE"."RECEPCIONISTA" MODIFY ("IDGERENTE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."RECEPCIONISTA" MODIFY ("ASISTENCIA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."RECEPCIONISTA" MODIFY ("NUMERO_TELEFONICO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."RECEPCIONISTA" MODIFY ("CODIGO_POSTAL" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."RECEPCIONISTA" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."RECEPCIONISTA" MODIFY ("GENERO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."RECEPCIONISTA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."RECEPCIONISTA" MODIFY ("CONTRASEÑA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."RECEPCIONISTA" MODIFY ("USUARIO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."RECEPCIONISTA" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RESERVACION
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."RESERVACION" ADD CONSTRAINT "RESERVACION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RESTAURANTE"."RESERVACION" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."RESERVACION" MODIFY ("NUMERO_PERSONA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."RESERVACION" MODIFY ("HORA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."RESERVACION" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."RESERVACION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."TICKET" ADD CONSTRAINT "TICKET_PK" PRIMARY KEY ("FOLIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "RESTAURANTE"."TICKET" MODIFY ("NUMERO_ORDEN" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."TICKET" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."TICKET" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."TICKET" MODIFY ("FORMA_PAGO" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."TICKET" MODIFY ("FECHA" NOT NULL ENABLE);
  ALTER TABLE "RESTAURANTE"."TICKET" MODIFY ("FOLIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."CLIENTE" ADD CONSTRAINT "CLIENTE_FK1" FOREIGN KEY ("NUMERO_TELEFONICO")
	  REFERENCES "RESTAURANTE"."ORDEN" ("NUMERO_ORDEN") ENABLE;
  ALTER TABLE "RESTAURANTE"."CLIENTE" ADD CONSTRAINT "CLIENTE_FK2" FOREIGN KEY ("FOLIO_TICKET")
	  REFERENCES "RESTAURANTE"."TICKET" ("FOLIO") ENABLE;
  ALTER TABLE "RESTAURANTE"."CLIENTE" ADD CONSTRAINT "CLIENTE_FK3" FOREIGN KEY ("ID_RESERVACION")
	  REFERENCES "RESTAURANTE"."RESERVACION" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDEN
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."ORDEN" ADD CONSTRAINT "ORDEN_FK1" FOREIGN KEY ("TIPO_PLATILLO")
	  REFERENCES "RESTAURANTE"."PLATILLO" ("TIPO") ENABLE;
  ALTER TABLE "RESTAURANTE"."ORDEN" ADD CONSTRAINT "ORDEN_FK2" FOREIGN KEY ("IDMESERO")
	  REFERENCES "RESTAURANTE"."MESERO" ("ID") ENABLE;
  ALTER TABLE "RESTAURANTE"."ORDEN" ADD CONSTRAINT "ORDEN_FK3" FOREIGN KEY ("FOLIO_TICKET")
	  REFERENCES "RESTAURANTE"."TICKET" ("FOLIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PLATILLO
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."PLATILLO" ADD CONSTRAINT "PLATILLO_FK1" FOREIGN KEY ("IDGERENTE")
	  REFERENCES "RESTAURANTE"."GERENTE" ("IDGERENTE") ENABLE;
  ALTER TABLE "RESTAURANTE"."PLATILLO" ADD CONSTRAINT "PLATILLO_FK2" FOREIGN KEY ("NUMERO_ORDEN")
	  REFERENCES "RESTAURANTE"."ORDEN" ("NUMERO_ORDEN") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."PRODUCTO" ADD CONSTRAINT "IDGERENTE_FK" FOREIGN KEY ("IDGERENTE")
	  REFERENCES "RESTAURANTE"."GERENTE" ("IDGERENTE") ENABLE;
  ALTER TABLE "RESTAURANTE"."PRODUCTO" ADD CONSTRAINT "IDPROVEEDOR_FK1" FOREIGN KEY ("IDPROVEEDOR")
	  REFERENCES "RESTAURANTE"."PROVEEDOR" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECEPCIONISTA
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."RECEPCIONISTA" ADD CONSTRAINT "IDGERENTE_FK1" FOREIGN KEY ("IDGERENTE")
	  REFERENCES "RESTAURANTE"."GERENTE" ("IDGERENTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RESERVACION
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."RESERVACION" ADD CONSTRAINT "RESERVACION_FK1" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "RESTAURANTE"."CLIENTE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TICKET
--------------------------------------------------------

  ALTER TABLE "RESTAURANTE"."TICKET" ADD CONSTRAINT "TICKET_FK1" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "RESTAURANTE"."CLIENTE" ("ID") ENABLE;
  ALTER TABLE "RESTAURANTE"."TICKET" ADD CONSTRAINT "TICKET_FK2" FOREIGN KEY ("NUMERO_ORDEN")
	  REFERENCES "RESTAURANTE"."ORDEN" ("NUMERO_ORDEN") ENABLE;
